#! /bin/sh   
compton -b --config .config/compton.conf --blur-method kawase --blur-strength 3 &
feh --bg-scale ~/doc/abwp.jpg &
xsetroot -cursor_name left_ptr &
polybar example &
nm-applet &
xinput set-prop 10 281 1
sxhkd &
xset dpms off &
bspc monitor -d I II III IV V VI VII  
dunst &
redshift &

bspc config border_width         3
bspc config window_gap          8
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a firefox state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
